"""Added even more columns to User

Revision ID: 438464ae8c82
Revises: 79674faaacbb
Create Date: 2023-03-10 10:35:02.092825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438464ae8c82'
down_revision = '79674faaacbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('menu', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'menu')
    # ### end Alembic commands ###
