"""Added more columns to User

Revision ID: 79674faaacbb
Revises: 58a80aeeaabe
Create Date: 2023-03-10 10:29:22.986419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79674faaacbb'
down_revision = '58a80aeeaabe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('restaurant', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    op.drop_column('users', 'restaurant')
    # ### end Alembic commands ###
